### ISSUE TITLE
not working on Moto g 2nd generation

### ISSUE THREAD

**Issue by sbprasad2000** [AbinashBishoyi/WhatsApp-Key-DB-Extractor-UnOfficial#9]
C:\WhatsApp-Key-DB-Extractor-UnOfficial\WhatsApp-Key-DB-Extractor-UnOfficial-ma
ter\WhatsApp\res\values-v23\styles.xml:5: error: Error retrieving parent for it
m: No resource found that matches the given name '@android:style/AlertDialog'.
C:\WhatsApp-Key-DB-Extractor-UnOfficial\WhatsApp-Key-DB-Extractor-UnOfficial-ma
ter\WhatsApp\res\values-v23\styles.xml:6: error: Error retrieving parent for it
m: No resource found that matches the given name '@android:style/DialogWindowTi
le'.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Andro
ibException: brut.common.BrutException: could not exec command: [C:\Users\BANUP
~1\AppData\Local\Temp\brut_util_Jar_4675704223377009733.tmp, p, --forced-packag
-id, 127, --min-sdk-version, 7, --target-sdk-version, 23, --version-code, 45089
, --version-name, 2.12.437, -F, C:\Users\BANUPR~1\AppData\Local\Temp\APKTOOL133
246992735078683.tmp, -0, arsc, -I, C:\Users\Banuprasad\apktool\framework\1.apk,
-S, C:\WhatsApp-Key-DB-Extractor-UnOfficial\WhatsApp-Key-DB-Extractor-UnOfficia
-master\WhatsApp\res, -M, C:\WhatsApp-Key-DB-Extractor-UnOfficial\WhatsApp-Key-
B-Extractor-UnOfficial-master\WhatsApp\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:374)
        at brut.androlib.Androlib.build(Androlib.java:277)
        at brut.androlib.Androlib.build(Androlib.java:250)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could no
 exec command: [C:\Users\BANUPR~1\AppData\Local\Temp\brut_util_Jar_467570422337
009733.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-ver
ion, 23, --version-code, 450895, --version-name, 2.12.437, -F, C:\Users\BANUPR~
\AppData\Local\Temp\APKTOOL1332246992735078683.tmp, -0, arsc, -I, C:\Users\Banu
rasad\apktool\framework\1.apk, -S, C:\WhatsApp-Key-DB-Extractor-UnOfficial\What
App-Key-DB-Extractor-UnOfficial-master\WhatsApp\res, -M, C:\WhatsApp-Key-DB-Ext
actor-UnOfficial\WhatsApp-Key-DB-Extractor-UnOfficial-master\WhatsApp\AndroidMa
ifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.ja
a:488)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\BANUPR~
\AppData\Local\Temp\brut_util_Jar_4675704223377009733.tmp, p, --forced-package-
d, 127, --min-sdk-version, 7, --target-sdk-version, 23, --version-code, 450895,
--version-name, 2.12.437, -F, C:\Users\BANUPR~1\AppData\Local\Temp\APKTOOL13322
6992735078683.tmp, -0, arsc, -I, C:\Users\Banuprasad\apktool\framework\1.apk, -
, C:\WhatsApp-Key-DB-Extractor-UnOfficial\WhatsApp-Key-DB-Extractor-UnOfficial-
aster\WhatsApp\res, -M, C:\WhatsApp-Key-DB-Extractor-UnOfficial\WhatsApp-Key-DB
Extractor-UnOfficial-master\WhatsApp\AndroidManifest.xml]

**Comment by nicolabeghin** [comment]
I have the same issue

**Comment by nicolabeghin** [comment]
fixed with [WhatsApp-Key-DB-Extractor-UnOfficial_fix_20160310.patch](https://gist.github.com/nicolabeghin/913a4ba298f11c965d69#file-whatsapp-key-db-extractor-unofficial_fix_20160310-patch)
